### ISSUE TITLE
Upload Problem

### ISSUE THREAD

**Issue by raschnepper** [hyperstudio/Annotation-Studio#127]
Twice this week users (one of which was Wyn in the MIT instance) and another (a student from UPenn in the public instance) were having the same issue.  When they both tried to upload a document (in Wyn's case it was a Word file, I am waiting for info from the UPenn student), the document would not stick.  The document was created--you could click on it in your Doc list--but the content was never there.  Editing the document in Draft mode revealed that the content of the document did not actually load.  The content would not load in either Draft or Published mode.  Metadata always loaded.  

Liam looked at the Wyn issue and could not figure it out, but now it is happening again.

**Comment by jamiefolsom** [comment]
I have once again tested, with both PDF and Word Doc, and cannot reproduce this issue. If people continue to report this, and can provide details, please add them in here, and reopen the issue, and I will see if I can reproduce. Thanks!
