### ISSUE TITLE
Error if you create a new document

### ISSUE THREAD

**Issue by danielcebrian** [hyperstudio/Annotation-Studio#151]
In new instances of Annotation studio I get this error:

Extracted source (around line #198):  
  # helper to determine if we should support content from the MEL catalog
  def catalogue_enabled?
    Tenant.current_tenant.mel_catalog_enabled
  end

  def catalog_content( doc )

Rails.root: /home/dcebrian/Dani/Aplicaciones/Webs/Annotation-Studio

Application Trace | Framework Trace | Full Trace
app/controllers/documents_controller.rb:198:in `catalogue_enabled?'
app/controllers/documents_controller.rb:189:in`catalog_texts'
app/controllers/documents_controller.rb:66:in `new'
config/initializers/quiet_assets.rb:6:in`call_with_quiet_assets'

**Comment by blms** [comment]
We no longer support MEL catalog.
